apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyerp-site
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: "study4.azurecr.io/crud-aspnetcore:latest"
        ports:
        - name: app
          containerPort: 80
      #imagePullSecrets:
      #  - name: study4containerreg