apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: "microsoft/mssql-server-linux"
        ports:
        - name: sqlserver
          containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "P@ssw0rd"
        - name: ACCEPT_EULA
          value: "Y"
      #imagePullSecrets:
      #  - name: study4containerreg